@startuml
!include <C4/C4_Container>

skinparam {
    backgroundColor #FAFAFA
    roundCorner 20
    shadowing true
    wrapWidth 200
}

Person(web_user, "Web User", "Клиент, использующий систему через веб-интерфейс")
Person(mobile_user, "Mobile User", "Клиент, использующий систему через мобильное приложение")
Person(tv_user, "SmartTV User", "Клиент, использующий систему через SmartTV")

System_Ext(recommend_system, "External Recommend System", "Внешняя рекомендательная система")
System_Ext(online_cinemas, "Online Cinemas", "Онлайн кинотеатры")
System_Ext(billing_system, "Billing System", "Платёжная система")
System_Ext(S3, "S3", "Файловое хранилище")

System_Boundary(c1, ) {
    Container(web_bff, "Web BFF", "Go", "BFF для веб-клиента")
    Container(mobile_bff, "Mobile BFF", "Go", "BFF для мобильного клиента")
    Container(tv_bff, "SmartTV BFF", "Go", "BFF для SmartTV")
    Container(api_gateway, "API Gateway", "Go", "Маршрутизирует трафик на BFF и сервисы")
    Container(auth_service, "Auth Service", "Go", "Отвечает за регистрацию, аутентификацию")
    ContainerDb(auth_db, "Auth DB", "PostgreSQL", "Хранит данные пользователей и сессии")
    Container(monolith, "Monolith", "Go", "Отвечает за управление пользователями, данными фильмов, платежами, подписками")
    ContainerDb(monolith_db, "Monolith DB", "PostgreSQL", "Хранит информацию о профилях пользователей, метаданных фильмов, платежей, подписках")
    Container(movies_service, "Movies Service", "Go", "Отвечает за регистрацию, настройку и управление метаданными устройств")
    ContainerDb(movies_db, "Movies DB", "PostgreSQL", "Хранит информацию о метаданных фильмов, платежей, подписках")
    Container(events_service, "Events Service", "Go", "Обрабатывает коммуникацию между сервисами на основе событий")
    Container(message_broker, "Message Broker", "Kafka", "Обеспечивает асинхронную доставку событий")
}

Rel(web_user, web_bff, "API-запросы", "HTTPS")
Rel(mobile_user, mobile_bff, "API-запросы", "HTTPS")
Rel(tv_user, tv_bff, "API-запросы", "HTTPS")

Rel(web_bff, api_gateway, "Маршрутизация запросов", "HTTP")
Rel(mobile_bff, api_gateway, "Маршрутизация запросов", "HTTP")
Rel(tv_bff, api_gateway, "Маршрутизация запросов", "HTTP")

Rel(api_gateway, auth_service, "Запросы аутентификации", "HTTP")
Rel(api_gateway, monolith, "Запросы профилей, платежей, подписок", "HTTP")
Rel(api_gateway, movies_service, "Запросы метаданных фильмов", "HTTP")
Rel(api_gateway, events_service, "Запросы событий", "HTTP")

Rel(auth_service, auth_db, "Читает/пишет", "TCP/IP")
Rel(monolith, monolith_db, "Читает/пишет", "TCP/IP")
Rel(movies_service, movies_db, "Читает/пишет", "TCP/IP")

Rel(auth_service, message_broker, "Публикует/потребляет события", "TCP/IP")
Rel(monolith, message_broker, "Публикует/потребляет события", "TCP/IP")
Rel(movies_service, message_broker, "Публикует/потребляет события", "TCP/IP")
Rel(events_service, message_broker, "Публикует/потребляет события", "TCP/IP")

Rel(monolith, recommend_system, "Отправляет/получает данные", "AMQP/MQTT")
Rel(monolith, online_cinemas, "Отправляет данные", "HTTPS")
Rel(monolith, S3, "Сохраняет данные", "HTTPS")
Rel(monolith, billing_system, "Платежи", "HTTPS")

@enduml
